[package]
name = "blitz"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_16"] }
libadwaita = "0.7.1"
relm4 = "0.9"
relm4-components = "0.9"
